import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {freshState,SAVE_KEY} from '../src/game.mjs';import {HOUSES} from '../src/content.mjs';
const b=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true,args:process.env.GPU?['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist']:['--enable-unsafe-swiftshader']});const errors=[],results=[];await mkdir('test-results',{recursive:true});
async function setup(position,extra={}){const s=Object.assign(freshState(),{started:true,coins:4000,day:3,position,inventory:{soup:2,apple:5,carrot:4,mushroom:3,egg:3},stats:{harvests:3,fish:2,sales:250,feeds:0,trips:0,cooked:2,festivals:0,races:0},...extra});const c=await b.newContext({viewport:{width:1440,height:960}});await c.addInitScript(({s,key})=>localStorage.setItem(key,JSON.stringify(s)),{s,key:SAVE_KEY});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});await p.goto(process.env.GAME_URL??'http://127.0.0.1:4173');await p.waitForFunction(()=>window.willowmere?.metrics().ready);await p.locator('#begin').click();await p.waitForTimeout(200);return{p,c};}
// Zoom the camera out first, as a player would, so far-off targets are on screen.
async function target(p,type,id){await p.mouse.move(720,480);for(let i=0;i<6;i++)await p.mouse.wheel(0,400);await p.waitForTimeout(250);const t=await p.evaluate(({type,id})=>willowmere.targets().find(t=>t.type===type&&(id===undefined||String(t.id)===String(id))),{type,id});await p.mouse.click(t.screen.x,t.screen.y);}
try{
 let {p,c}=await setup({x:46,z:-12});await p.keyboard.press('e');await p.waitForFunction(()=>document.querySelector('#location-text').textContent.includes('jeep'));const start=await p.evaluate(()=>willowmere.metrics().position);await p.keyboard.down('d');await p.waitForTimeout(700);await p.keyboard.up('d');const moved=await p.evaluate(()=>willowmere.metrics().position);assert.ok(Math.hypot(start.x-moved.x,start.z-moved.z)>2);await p.screenshot({path:'test-results/09-jeep.png'});await p.locator('[data-panel="map"]').click();await p.locator('[data-action="find"][data-type="travel"]').click();await p.waitForFunction(()=>willowmere.metrics().location==='country',null,{timeout:15000});assert.equal((await p.evaluate(()=>willowmere.snapshot())).stats.trips,1);await p.screenshot({path:'test-results/10-country.png'});await target(p,'shop','country');await p.waitForSelector('#modal-title:has-text("The hillside market")',{timeout:15000});await p.locator('[data-action="sell"][data-id="carrot"][data-one="true"]').click();assert.equal((await p.evaluate(()=>willowmere.snapshot())).stats.sales,273);await p.getByRole('button',{name:'Close panel',exact:true}).click();await p.locator('[data-panel="map"]').click();await p.locator('[data-action="find"][data-type="house"][data-id="0"]').click();await p.waitForFunction(()=>willowmere.metrics().location==='interior',null,{timeout:25000});results.push({name:'jeep driving, east road, country trade premium and home return',pass:true});await c.close();
 ({p,c}=await setup({x:5,z:-6.5},{bike:true}));await p.keyboard.press('e');await p.waitForFunction(()=>document.querySelector('#location-text').textContent.includes('motorcycle'));await p.keyboard.down('d');await p.waitForTimeout(450);await p.keyboard.up('d');await p.keyboard.press('e');await p.waitForFunction(()=>!document.querySelector('#location-text').textContent.includes('motorcycle'));results.push({name:'motorcycle boarding, driving and dismount',pass:true});await c.close();
 ({p,c}=await setup({x:17,z:-13},{upgrades:{farm:0,pond:0,pen:2,house:0,kitchen:0}}));await p.keyboard.press('e');assert.equal((await p.evaluate(()=>willowmere.snapshot())).fedDay,3);await target(p,'collect');await p.waitForFunction(()=>willowmere.snapshot().collectedDay===3,null,{timeout:10000});assert.equal((await p.evaluate(()=>willowmere.snapshot())).inventory.milk,1);results.push({name:'animal feeding and egg/milk collection in world',pass:true});await c.close();
 ({p,c}=await setup({x:22,z:28}));await p.keyboard.press('e');await p.locator('[data-type="festival"][data-id="soup"]').click();assert.equal((await p.evaluate(()=>willowmere.snapshot())).stats.festivals,1);await p.screenshot({path:'test-results/11-harvest-supper.png'});await p.locator('[data-action="startRace"]').click();for(const point of [{x:4,z:24},{x:24,z:30},{x:28,z:12},{x:30,z:-4}]){
  // Steer with the same screen-relative WASD controls as a player. Diagnostics only read position.
  for(let i=0;i<140;i++){const at=await p.evaluate(()=>willowmere.metrics().position);const dx=point.x-at.x,dz=point.z-at.z;if(Math.hypot(dx,dz)<1.5)break;const x=dx*Math.cos(.38)-dz*Math.sin(.38),z=dx*Math.sin(.38)+dz*Math.cos(.38),keys=[];if(Math.abs(x)>.6)keys.push(x>0?'d':'a');if(Math.abs(z)>.6)keys.push(z>0?'s':'w');await p.keyboard.down('Shift');for(const k of keys)await p.keyboard.down(k);await p.waitForTimeout(100);for(const k of keys)await p.keyboard.up(k);await p.keyboard.up('Shift');}
 }await p.waitForFunction(()=>willowmere.snapshot().stats.races===1,null,{timeout:5000});results.push({name:'cooking festival submission and ordered three-checkpoint running course',pass:true});await c.close();
 for(const h of HOUSES){({p,c}=await setup({x:h.x+Math.sin(h.rot)*4.7,z:h.z+Math.cos(h.rot)*4.7}));await p.keyboard.press('e');await p.waitForFunction(()=>willowmere.metrics().location==='interior');await p.keyboard.press('e');await p.waitForFunction(()=>willowmere.metrics().location==='village');await c.close();}results.push({name:'all ten household doors enter and return to their village doorstep',pass:true});
 ({p,c}=await setup({x:-15,z:0}));await p.locator('[data-panel="settings"]').click();const downloadPromise=p.waitForEvent('download');await p.locator('[data-action="export"]').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/^willowmere-day-3.json$/);const imported=freshState();imported.coins=777;imported.chapter=2;imported.started=true;p.once('dialog',dialog=>dialog.accept());await p.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await p.waitForFunction(()=>willowmere.snapshot().coins===777);assert.equal((await p.evaluate(()=>willowmere.snapshot())).chapter,2);results.push({name:'portable save export and validated import',pass:true});await c.close();
 assert.deepEqual(errors,[]);await writeFile('test-results/activity-results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));
}catch(error){console.error(error);throw error;}finally{await b.close();}
