import {landFish} from './fishing-controls.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {freshState,SAVE_KEY} from '../src/game.mjs';
const browser=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true,args:['--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const base=process.env.GAME_URL??'http://127.0.0.1:4173';const errors=[],results=[];await mkdir('test-results',{recursive:true});
async function setup(seed,mobile=false){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:960},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1});if(seed)await context.addInitScript(({key,seed})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(seed));},{key:SAVE_KEY,seed});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});await page.goto(base);await page.waitForFunction(()=>window.willowmere?.metrics().ready,null,{timeout:60000});return{page,context};}
const snapshot=p=>p.evaluate(()=>willowmere.snapshot());
const close=p=>p.getByRole('button',{name:'Close panel',exact:true}).click();
async function clickTarget(p,type,id){const target=await p.evaluate(({type,id})=>willowmere.targets().find(t=>t.type===type&&(id===undefined||String(t.id)===String(id))),{type,id});assert.ok(target,`target ${type} exists`);await p.mouse.click(target.screen.x,target.screen.y);}
async function find(p,type,id){await p.locator('[data-panel="map"]').click();await p.locator(`[data-action="find"][data-type="${type}"][data-id="${id}"]`).click();}
try{
 const {page:p,context}=await setup();await p.screenshot({path:'test-results/01-welcome.png'});await p.locator('#begin').click();await p.waitForTimeout(300);await p.screenshot({path:'test-results/02-village.png'});results.push({name:'fresh village',metrics:await p.evaluate(()=>willowmere.metrics())});
 await p.locator('[data-panel="people"]').click();assert.equal(await p.locator('.resident').count(),24);await p.locator('[data-action="find"][data-person="ada"]').click();await p.waitForSelector('#modal-title:has-text("Ada")',{timeout:25000});assert.ok((await snapshot(p)).met.ada);await close(p);await p.locator('[data-panel="journal"]').first().click();await p.locator('[data-action="claim"]').click();assert.equal((await snapshot(p)).chapter,1);await close(p);results.push({name:'meet Ada and complete chapter one',pass:true});
 await find(p,'bed','0');await p.waitForSelector('#modal-title:has-text("A little beginning")',{timeout:25000});await p.locator('[data-action="plant"][data-id="carrot"]').click();await p.keyboard.press('e');assert.ok((await snapshot(p)).beds[0].watered);await p.waitForFunction(()=>{const s=willowmere.snapshot();return s.elapsed-s.beds[0].planted>=32;},null,{timeout:45000});await p.keyboard.press('e');assert.equal((await snapshot(p)).stats.harvests,1);results.push({name:'plant, water, timed growth and harvest with real controls',pass:true});
 await find(p,'house','0');await p.waitForFunction(()=>willowmere.metrics().location==='interior',null,{timeout:20000});await p.waitForTimeout(200);await p.screenshot({path:'test-results/03-home.png'});results.push({name:'enter furnished home',metrics:await p.evaluate(()=>willowmere.metrics())});
 await p.locator('[data-panel="bag"]').click();assert.ok(await p.getByRole('heading',{name:'Carrot',exact:true}).count());await close(p);const before=await snapshot(p);await p.reload();await p.waitForFunction(()=>window.willowmere?.metrics().ready);assert.equal((await snapshot(p)).stats.harvests,before.stats.harvests);assert.equal((await snapshot(p)).chapter,1);await context.close();
 const rich=freshState();rich.started=true;rich.coins=2500;rich.day=3;rich.stats.sales=250;rich.position={x:12,z:10.6};rich.inventory={carrot:8,mushroom:4,perch:2,apple:6,egg:4,seed_carrot:4};rich.upgrades={farm:2,pond:2,pen:2,house:1,kitchen:2};rich.trees=[{kind:'apple',day:1,picked:0},{kind:'peach',day:1,picked:0},null];rich.elapsed=100;rich.beds=rich.beds.map((b,i)=>i<12?{crop:['carrot','radish','pumpkin','berry'][i%4],watered:true,planted:i%3?0:90}:null);
 const {page:q,context:qc}=await setup(rich);await q.locator('#begin').click();await q.waitForTimeout(400);await q.screenshot({path:'test-results/04-growing-farm.png'});await q.keyboard.press('e');await landFish(q);assert.equal((await snapshot(q)).stats.fish,1);results.push({name:'rod fishing with bite and tension',pass:true});
 await find(q,'shop','market');await q.waitForSelector('#modal-title:has-text("The village market")',{timeout:18000});await q.locator('[data-action="tab"][data-id="sell"]').click();await q.locator('[data-action="sell"][data-id="carrot"][data-one="true"]').click();assert.equal((await snapshot(q)).inventory.carrot,7);await q.locator('[data-action="tab"][data-id="outfits"]').click();await q.locator('[data-type="outfit"][data-id="rose"]').click();assert.equal((await snapshot(q)).outfit,'rose');await q.locator('[data-action="tab"][data-id="kids"]').click();await q.locator('[data-type="kidOutfit"][data-id="rain"]').click();assert.equal((await snapshot(q)).kidOutfit,'rain');await q.locator('[data-action="tab"][data-id="furniture"]').click();await q.locator('[data-type="furniture"][data-id="books"]').click();assert.ok((await snapshot(q)).furniture.includes('books'));await q.screenshot({path:'test-results/05-shop.png'});await close(q);results.push({name:'trade, adult outfit, child outfit and furniture purchases',pass:true});
 await find(q,'house','0');await q.waitForFunction(()=>willowmere.metrics().location==='interior',null,{timeout:18000});await q.screenshot({path:'test-results/06-furnished-home.png'});await qc.close();
 const atStove=structuredClone(rich);atStove.position={x:0,z:-8.8};const{page:r,context:rc}=await setup(atStove);await r.locator('#begin').click();await r.keyboard.press('e');await r.waitForFunction(()=>willowmere.metrics().location==='interior');
 await r.waitForTimeout(400);await clickTarget(r,'kitchen');await r.waitForSelector('#modal-title:has-text("A recipe passed down")',{timeout:12000});await r.locator('[data-type="cook"][data-id="soup"]').click();assert.equal((await snapshot(r)).inventory.soup,1);results.push({name:'interior kitchen cooking',pass:true});await close(r);await clickTarget(r,'bedroom');await r.waitForSelector('#modal-title:has-text("Home, at last")',{timeout:12000});await r.locator('[data-action="sleep"]').click();assert.equal((await snapshot(r)).day,4);await clickTarget(r,'exit');await r.waitForFunction(()=>willowmere.metrics().location==='village',null,{timeout:10000});await rc.close();
 const{page:m,context:mc}=await setup(rich,true);await m.locator('#begin').tap();await m.screenshot({path:'test-results/07-mobile.png'});const x0=(await m.evaluate(()=>willowmere.metrics())).position.x;const stick=await m.locator('#joystick').boundingBox();await m.mouse.move(stick.x+45,stick.y+45);await m.mouse.down();await m.mouse.move(stick.x+72,stick.y+45);await m.waitForTimeout(600);await m.mouse.up();assert.notEqual((await m.evaluate(()=>willowmere.metrics())).position.x,x0);await m.locator('[data-panel="people"]').tap();await m.screenshot({path:'test-results/08-mobile-directory.png'});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await m.locator('.resident').count(),24);await close(m);await m.locator('[data-panel="settings"]').click();await m.locator('#quality').selectOption('battery');assert.equal((await snapshot(m)).settings.quality,'battery');results.push({name:'390px mobile layout, joystick, directory and graphics settings',pass:true,metrics:await m.evaluate(()=>willowmere.metrics())});await mc.close();
 assert.deepEqual(errors,[]);await writeFile('test-results/browser-results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));
}finally{await browser.close();}
