import {landFish} from './fishing-controls.mjs';
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {freshState,SAVE_KEY} from '../src/game.mjs';
const url=process.env.GAME_URL??'http://127.0.0.1:4173',b=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});const errors=[],reports=[];await mkdir('test-results',{recursive:true});
async function setup(seed,mobile=false){const c=await b.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:960},isMobile:mobile,hasTouch:mobile});if(seed)await c.addInitScript(({seed,key})=>localStorage.setItem(key,JSON.stringify(seed)),{seed,key:SAVE_KEY});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});await p.goto(url);await p.waitForFunction(()=>window.willowmere?.metrics().ready,null,{timeout:90000});return{p,c};}
try{
 let{p,c}=await setup();await p.locator('#begin').click();await p.keyboard.down('d');await p.waitForTimeout(350);await p.keyboard.up('d');assert.ok((await p.evaluate(()=>willowmere.metrics())).position.x>-15);await p.locator('[data-panel="journal"]').first().click();assert.ok(await p.getByText('Meet Grandmother Ada',{exact:true}).count());await p.getByRole('button',{name:'Close panel',exact:true}).click();await p.waitForTimeout(150);await p.screenshot({path:'test-results/release-desktop.png'});reports.push({desktop:await p.evaluate(()=>willowmere.metrics())});await c.close();
 const s=freshState();s.position={x:9,z:16.8};({p,c}=await setup(s));await p.locator('#begin').click();await p.keyboard.press('e');await landFish(p,{screenshot:'test-results/release-fishing.png'});assert.equal((await p.evaluate(()=>willowmere.snapshot())).stats.fish,1);await c.close();
 const orchard=freshState();orchard.position={x:-28,z:20};({p,c}=await setup(orchard));await p.locator('#begin').click();await p.keyboard.press('e');await p.locator('[data-action="plantTree"][data-id="apple"]').click();assert.equal((await p.evaluate(()=>willowmere.snapshot())).trees[0].kind,'apple');await c.close();
 const hunt=freshState();hunt.position={x:-43,z:37};({p,c}=await setup(hunt));await p.locator('#begin').click();await p.keyboard.press('e');await p.waitForFunction(()=>document.querySelector('[data-action="track"]'));await p.waitForFunction(()=>{const x=parseFloat(document.querySelector('#fish-cursor').style.left);return x>42&&x<58;},null,{polling:16});await p.keyboard.press('Space');assert.equal((await p.evaluate(()=>willowmere.snapshot())).inventory.game,2);await c.close();
 ({p,c}=await setup(null,true));await p.locator('#begin').tap();await p.waitForTimeout(350);assert.equal(await p.locator('.stamina').isVisible(),true);await p.locator('[data-panel="settings"]').tap();await p.locator('#quality').selectOption('battery');await p.getByRole('button',{name:'Close panel',exact:true}).tap();await p.screenshot({path:'test-results/release-mobile.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);reports.push({mobile:await p.evaluate(()=>willowmere.metrics())});await c.close();
 assert.deepEqual(errors,[]);console.log(JSON.stringify({url,reports,errors},null,2));await writeFile('test-results/release-results.json',JSON.stringify({url,reports,errors},null,2));
}finally{await b.close();}
