// The fixed fighting kits of the disguises (fetched with the box, never in the first load). Ported from Zoo Garden (cute_game
// combat.ts disguise(), skill-info.ts DISGUISE_INFO, skill-sounds.ts DISGUISE, content.ts disguise skills): wearing a disguise replaces ALL
// four skills with its own, never levelled. A row is {op, icon, name, short?, cd, sound, pose, text}; `sp` names a weapon special of
// skills-special.mjs that the row reuses (Zoo's uniform kits do this) and then only the cooldown / icon / short name are set here.
// kitInfo() joins both into one cached object per skill, so asking for it every frame makes nothing.
import { SPECIALS } from './skills-special.mjs';

const K = (op, icon, name, cd, sound, pose, text, short) => ({ op, icon, name, cd, sound, pose, text, short });
const S = (sp, icon, cd, short) => ({ sp, op: sp, icon, cd, short });
/** disguise id -> its four skills (keys 1 2 3 4). The two marked NEW are changes against Zoo Garden, made so that no two kits share an effect. */
export const KITS = {
  dz_ninja: [K('clones', '👥', 'Shadow clones', 14, 'poof', 'w', 'Four shadow clones fight beside you for 8 s, each hit ×0.5 damage. Creatures within 8 m of a clone attack it instead of you; each has 25% of your health and vanishes in a puff when it runs out.', 'Clones'), K('stealth', '👤', 'Vanish', 12, 'poof', 'w', 'Vanish for 5 s: enemies lose you, and your next hit does triple damage.'), K('backstab', '⚡', 'Shadow strike', 6, 'swing', 's', 'Blink behind the nearest enemy within 12 m: ×3 damage and stunned for 1 s.', 'Strike'), K('smoke', '💨', 'Smoke bomb', 12, 'poof', 'w', 'A smoke cloud lasts 5 s within 5 m: enemies inside are blinded and you stay hidden while inside.', 'Smoke')],
  dz_mage: [K('fireball', '🔥', 'Great fireball', 5, 'magic', 'a', 'Charge 0.8 s, then hurl a great fireball at the nearest enemy within 14 m: ×3.5 damage in a 5 m blast, enemies thrown up.', 'Fireball'), K('teleport', '✨', 'Blink', 5, 'magic', 'w', 'Blink 8 m ahead.'), K('sheep', '🐑', 'Sheep spell', 12, 'magic', 'a', 'Turn the nearest enemy within 12 m, and up to 2 more within 3 m of it, into sheep for 6 s: tiny, slow and harmless (a boss is only slowed).', 'Sheep'), K('blackhole', '🌀', 'Black hole', 13, 'magic', 'a', 'A black hole at your target pulls enemies within 8 m for 3 s, then bursts: ×3 damage within 5 m.', 'Hole')],
  dz_knight: [K('shield', '🛡️', 'Shield block', 8, 'hit', 'w', 'Raise your shield for 4 s: every blow from in front of you is blocked, and shots that hit it fly back at their shooter for ×1.5 damage.', 'Shield'), K('charge', '🐎', 'Charge', 7, 'swing', 's', 'Charge 11 m forward, untouchable, ×3 damage to every enemy on the way.'), K('taunt', '📯', 'Challenge', 12, 'alert', 'w', 'Challenge every enemy within 12 m for 6 s: they are drawn to you and you take far less damage.', 'Challenge'), K('holy', '🗡️', 'Holy blade', 12, 'magic', 's', 'After 0.8 s a holy blade strikes your target: ×4 damage within 3.5 m, stuns 1 s.', 'Holy')],
  dz_mecha: [K('tank', '🚜', 'Tank mode', 12, 'zap', 'w', 'Tank mode for 6 s: a 2 m electric shockwave every 0.25 s, ×1 damage, stunned 0.3 s.', 'Tank'), K('turret', '🗼', 'Tesla turret', 14, 'zap', 'w', 'Drop a tesla turret that fires shock bolts for 12 s, ×0.55 damage each. Creatures may attack it (45% of your health).', 'Turret'), K('missiles', '🚀', 'Shock missiles', 7, 'zap', 'a', 'Up to 6 guided shock missiles at enemies within 16 m: ×2 damage and a 2 m electric burst.', 'Missiles'), K('energyshield', '🔰', 'Energy shield', 16, 'magic', 'w', 'Energy shield: no damage for 4 s and 20% health back.', 'Barrier')],
  dz_dino: [K('devour', '😋', 'Devour', 9, 'crit', 's', 'Bite an enemy within 3.2 m: a weak one (under 40% health) is swallowed whole and heals you 25%; otherwise ×3 damage (a boss is never swallowed).'), K('tail', '💨', 'Tail sweep', 5, 'swing', 's', 'A tail sweep all around: ×1.8 damage within 3.6 m and a big knock-back.', 'Tail'), K('roar', '📢', 'Terrifying roar', 12, 'alert', 'w', 'Roar: enemies within 9 m flee in fear for 4 s (a boss is only slowed).', 'Roar'), K('giant', '🦖', 'Giant form', 18, 'boom', 'w', 'Giant form for 10 s: twice as big, +60% damage, a quarter less damage taken, and your steps shake the ground.', 'Giant')],
  dz_fairy: [K('heal', '💖', 'Healing flowers', 12, 'magic', 'w', 'Healing flowers for 8 s: stay within 4 m to heal 3% every half second.', 'Flowers'), K('hover', '🦋', 'Float', 10, 'magic', 'w', 'Float for 8 s: ground attacks miss you.'), K('charm', '💘', 'Fairy charm', 14, 'magic', 'a', 'Charm the nearest enemy within 12 m for 8 s: it fights the other creatures (a boss is only slowed).', 'Charm'), K('tree', '🌳', 'Binding tree', 14, 'magic', 'w', 'A binding tree grows 3 m ahead for 6 s: its roots hold every enemy within 5 m for 4 s, and it lashes one every 1 s for ×0.8 damage. Creatures may attack it (80% of your health).', 'Tree')],
  dz_pirate: [K('cannon', '💣', 'Deck cannon', 12, 'boom', 'w', 'Set a deck cannon that fires exploding shells for 10 s, ×1.4 damage each. Creatures may attack it (50% of your health).', 'Cannon'), K('hook', '🪝', 'Hook', 6, 'swing', 'a', 'Hook the nearest enemy within 14 m and pull it to you: ×1.5 damage, stunned 2 s.'), K('parrot', '🦜', 'Scout parrot', 10, 'alert', 'a', 'A scout parrot flies out for 8 s, pecking enemies (×0.4 damage) and marking them for 8 s: marked enemies take +50% damage.', 'Parrot'), K('cannons', '🏴‍☠️', 'Ship broadside', 14, 'boom', 'a', 'A pirate ship\'s broadside: 12 cannonballs land around your target, ×1.4 damage within 1.8 m each.', 'Broadside')],
  dz_superhero: [K('flight', '🦸', 'Take flight', 3, 'magic', 'w', 'Fly for 12 s (press again to land): ground attacks miss you.', 'Fly'), K('dive', '☄️', 'Meteor dive', 6, 'boom', 's', 'Dive 4 m ahead and crash: ×2 damage within 5 m, ×4 if you were flying; stuns 1 s.', 'Dive'), K('sweep', '👀', 'Laser gaze', 7, 'zap', 'a', 'Twin eye lasers sweep a 13 m line, 1 m wide, across the front for 1.2 s: ×1 damage per touch.', 'Gaze'), K('boulder', '🪨', 'Boulder throw', 10, 'boom', 'a', 'Lob a giant rock at the nearest enemy within 14 m (8 m ahead if none): lands in 0.6 s for ×3.2 damage in a 4.5 m blast, launching enemies upward.', 'Boulder')],
  dz_vampire: [K('drain', '🩸', 'Life drain', 7, 'magic', 'a', 'Drain your target for 2.1 s: 7 bites of ×0.7 damage, each heals you 3.5%.', 'Drain'), K('bats', '🦇', 'Bat form', 9, 'poof', 'w', 'Become bats for 2.5 s: untouchable.', 'Bat form'), K('batcircle', '🦇', 'Bat swarm', 12, 'poof', 'w', 'Five bats circle you for 8 s, biting enemies and healing you.', 'Swarm'), K('bloodnova', '🌕', 'Blood moon', 15, 'magic', 'w', 'Blood moon for 6 s: enemies within 7 m take ×0.3 damage every 0.5 s and every hit heals you 40%.', 'Blood moon')],
  dz_snowman: [K('snowball', '⚪', 'Rolling snowball', 7, 'freeze', 'a', 'Roll a growing snowball 21 m: ×3 damage to everything it passes, stunned 2 s.', 'Snowball'), K('decoy', '⛄', 'Snow decoy', 12, 'poof', 'w', 'A snow decoy stands 2.5 m ahead for 6 s with 60% of your health: creatures within 8 m attack it instead of you. When it melts or breaks it bursts for ×2.5 damage within 4 m and freezes them 2 s.', 'Decoy'), K('icefloor', '🧊', 'Ice rink', 12, 'freeze', 'w', 'An 8 s ice rink 6 m around you: enemies on it are slowed.', 'Rink'), K('iceage', '❄️', 'Ice age', 16, 'freeze', 'w', 'Freeze every enemy within 8 m for 3 s, then shatter them for ×2.8 damage.', 'Ice age')],
  dz_army: [K('popgun', '🍾', 'Cork popgun', 6, 'pop', 'a', 'Pop 5 toy corks in a fan, 12 m ahead: ×1.2 damage each.', 'Popgun'), K('sandbag', '🧱', 'Sandbag wall', 10, 'hit', 'w', 'Stack a sandbag wall round you for 6 s: +60 defence while you stand inside its 2.6 m ring; enemies inside are pushed out (×0.5 damage). The wall has 90% of your health and creatures may attack it.', 'Sandbags'), K('flare', '🎇', 'Signal flare', 12, 'shoot', 'a', 'Fire a signal flare over the nearest enemy within 12 m: after 0.5 s every enemy within 5 m is dazzled for 4 s and marked for 6 s (+50% damage taken).', 'Flare'), K('airdrop', '🪂', 'Supply drop', 16, 'boom', 'a', '5 supply crates parachute around the nearest enemy within 14 m: each lands for ×2 damage within 2.2 m, and the supplies heal you 15%.', 'Airdrop')],
  dz_navy: [S('anchor', '⚓', 7, 'Anchor'), K('surfride', '🌊', 'Wave ride', 7, 'splash', 's', 'Ride a wave 9.1 m forward, untouchable, ×1.4 damage to every enemy on the way.', 'Surf'), K('whistle', '🎶', 'Bosun\'s whistle', 12, 'alert', 'w', 'Blow the bosun\'s whistle: every enemy within 8 m stands to attention, stunned for 2.5 s.', 'Whistle'), K('lighthouse', '🔦', 'Lighthouse beam', 15, 'level', 'w', 'A little lighthouse stands beside you for 6 s; its beam sweeps round every 2 s: ×1.2 damage and a 1.5 s dazzle to each enemy within 12 m it passes.', 'Beacon')],
  dz_aodai: [S('lotus', '🪷', 6, 'Lotus'), K('ribbon', '🎀', 'Silk ribbon glide', 8, 'swing', 's', 'Glide 8.4 m on a silk ribbon, untouchable, then move 30% faster for 3 s.', 'Ribbon'), K('fan', '🪭', 'Paper fan breeze', 12, 'swing', 'a', 'Open a paper fan: a gust through a 100° cone 7 m ahead, ×1.2 damage, enemies blown back and slowed 3 s.', 'Fan'), K('lanterns', '🏮', 'Lantern festival', 15, 'level', 'w', '8 paper lanterns drift out 4 m around you and burst one after another: ×1.6 damage within 2.4 m each, and each heals you 2%.', 'Lanterns')],
  dz_aodai_man: [S('dragon', '🐉', 7, 'Dragon'), K('kite', '🪁', 'Kite glide', 10, 'magic', 'w', 'Glide under a kite for 5 s, 30% faster: melee attacks miss you.', 'Kite'), K('ink', '🖌️', 'Ink circle', 12, 'poof', 'w', 'Brush an ink circle 5 m around you: ×0.8 damage, and enemies inside are held for 3 s.', 'Ink'), K('dragondance', '🐲', 'Dragon dance', 15, 'level', 'w', 'A dragon dance circles you for 5 s: ×0.7 damage every 0.5 s to every enemy within 4.2 m.', 'Dance')],
  dz_usa: [S('eagle', '🦅', 7, 'Eagle'), K('starshield', '🛡️', 'Star shield', 9, 'hit', 'w', 'Raise a star shield: no damage for 3 s, and enemies within 3 m are bashed back (×1 damage).', 'Shield'), K('torch', '🔥', 'Liberty torch', 12, 'magic', 'w', 'Raise the liberty torch: +30% damage for 6 s, 10% health back, and enemies within 6 m are dazzled for 2 s.', 'Torch'), K('fireworks', '🎆', 'Fireworks finale', 15, 'boom', 'a', '10 fireworks shoot up over enemies within 14 m and burst: ×1.5 damage within 2.2 m each.', 'Fireworks')],
  dz_vietnam: [S('goldstar', '⭐', 7, 'Star'), K('bamboo', '🎋', 'Bamboo vault', 7, 'swing', 's', 'Pole-vault 8 m forward on a bamboo pole, untouchable, landing for ×1.4 damage within 3 m.', 'Vault'), K('drum', '🥁', 'Bronze drum', 12, 'boom', 'w', 'Beat the bronze drum 3 times: each beat deals ×0.6 damage within 7 m and pushes enemies back; the last stuns them 1.5 s.', 'Drum'), K('bigstar', '🌟', 'Great golden star', 15, 'crit', 'a', 'A great golden star falls on the nearest enemy within 14 m after 0.7 s: ×4 damage within 5 m, and enemies there are slowed 3 s.', 'Big star')],
};
/**
 * A disguise fights with its own basic attack (Zoo content.ts DISGUISES[id].weapon), whatever weapon is worn under it:
 * the same fields as a gear.mjs weapon (kind, range, cooldown, arc, fx, shot, spread).
 */
const W = (kind, range, cooldown, extra) => ({ kind, range, cooldown, ...extra });
export const KIT_WEAPON = {
  dz_superhero: W('fist', 1.3, .28), dz_ninja: W('sword', 2.3, .3, { arc: .3, fx: '#c9c9ff' }), dz_mage: W('gun', 10, .7, { shot: 'fireball' }), dz_knight: W('sword', 2.8, .6, { arc: .2, fx: '#fff3c4' }),
  dz_mecha: W('gun', 11, .22, { shot: 'volt' }), dz_dino: W('sword', 2.4, .55, { arc: .4, fx: '#ffffff' }), dz_fairy: W('gun', 10, .42, { shot: 'bubble' }), dz_army: W('gun', 12, .35, { shot: 'cork', spread: 2 }),
  dz_navy: W('sword', 2.4, .55, { arc: .4, fx: '#9fd6ff' }), dz_aodai: W('gun', 10, .42, { shot: 'bubble' }), dz_aodai_man: W('sword', 2.4, .55, { arc: .4, fx: '#ffd84a' }), dz_usa: W('gun', 11, .4, { shot: 'star' }),
  dz_vietnam: W('gun', 10, .42, { shot: 'fire' }), dz_pirate: W('gun', 8, .6, { shot: 'spike', spread: 3 }), dz_vampire: W('sword', 2.3, .45, { arc: .3, fx: '#b0203a' }), dz_snowman: W('gun', 10, .4, { shot: 'ice' }),
};
export const isKit = id => !!KITS[id];
const cache = {};
/** One skill of a kit, ready for the HUD and the cast: {op, sp, icon, name, short, cd, sound, pose, text, sid}. Specials come from skills-special.mjs. */
export function kitInfo(id, index) {
  const key = id + index; let k = cache[key]; if (k) return k;
  const row = KITS[id]?.[index]; if (!row) return null;
  const sp = row.sp ? SPECIALS[row.sp] : null;
  return cache[key] = { op: row.op, sp: row.sp ?? '', icon: row.icon, name: sp?.name ?? row.name, short: row.short ?? '', cd: row.cd, sound: sp?.sound ?? row.sound, pose: sp?.pose ?? row.pose, text: sp?.text ?? row.text, dmg: sp?.damage ?? 0, sid: key };
}
/** The accent colour of a disguise (the reference's disguise colour): looks and the weapon-free trail use it. */
export const KIT_COLOR = { dz_ninja: '#c9c9ff', dz_mage: '#7f6fff', dz_knight: '#fff3c4', dz_mecha: '#6ff2ff', dz_dino: '#5fbf5a', dz_fairy: '#ff9ec8', dz_pirate: '#ffc93c', dz_superhero: '#3f6fff', dz_vampire: '#b0203a', dz_snowman: '#9fe8ff', dz_army: '#6b7a3a', dz_navy: '#1e3a8a', dz_aodai: '#ff8fb1', dz_aodai_man: '#23408f', dz_usa: '#d6283a', dz_vietnam: '#da251d' };
