// The fixed fighting kits of the disguises (fetched with the box, never in the first load). Ported from Zoo Garden (cute_game
// combat.ts disguise(), skill-info.ts DISGUISE_INFO, skill-sounds.ts DISGUISE, content.ts disguise skills): wearing a disguise replaces ALL
// four skills with its own, never levelled. A row is {op, icon, name, short?, cd, sound, pose, text}; `sp` names a weapon special of
// skills-special.mjs that the row reuses (Zoo's uniform kits do this) and then only the cooldown / icon / short name are set here.
// kitInfo() joins both into one cached object per skill, so asking for it every frame makes nothing.
import { SPECIALS } from './skills-special.mjs';

const K = (op, icon, name, cd, sound, pose, text, short) => ({ op, icon, name, cd, sound, pose, text, short });
const S = (sp, icon, cd, short) => ({ sp, op: sp, icon, cd, short });
/** disguise id -> its four skills (keys 1 2 3 4). The two marked NEW are changes against Zoo Garden, made so that no two kits share an effect. */
export const KITS = {
  dz_ninja: [K('clones', '👥', 'Shadow clones', 14, 'poof', 'w', 'Two shadow clones fight beside you for 8 s.', 'Clones'), K('stealth', '👤', 'Vanish', 12, 'poof', 'w', 'Vanish for 5 s: enemies lose you, and your next hit does triple damage.'), K('backstab', '⚡', 'Shadow strike', 6, 'swing', 's', 'Blink behind the nearest enemy within 12 m: ×3 damage and stunned for 1 s.', 'Strike'), K('smoke', '💨', 'Smoke bomb', 12, 'poof', 'w', 'A smoke cloud lasts 5 s within 5 m: enemies inside are blinded and you stay hidden while inside.', 'Smoke')],
  dz_mage: [K('fireball', '🔥', 'Great fireball', 5, 'magic', 'a', 'Charge 0.8 s, then a great fireball: ×3 damage and a 4 m blast (×1.8) that stuns 2 s.', 'Fireball'), K('teleport', '✨', 'Blink', 5, 'magic', 'w', 'Blink 8 m ahead.'), K('sheep', '🐑', 'Sheep spell', 12, 'magic', 'a', 'Turn enemies within 3 m of your target into sheep for 6 s: tiny, slow and harmless (a boss is only slowed).', 'Sheep'), K('blackhole', '🌀', 'Black hole', 13, 'magic', 'a', 'A black hole pulls enemies within 7 m for 3 s, dealing pulses within 5 m, then bursts for ×3 damage.', 'Hole')],
  dz_knight: [K('shield', '🛡️', 'Raise shield', 8, 'magic', 'w', 'Raise your shield: no damage for 4 s.', 'Shield'), K('charge', '🐎', 'Charge', 7, 'swing', 's', 'Charge 11 m forward, untouchable, ×3 damage to every enemy on the way.'), K('taunt', '📯', 'Challenge', 12, 'alert', 'w', 'Challenge every enemy within 12 m for 6 s: they are drawn to you and you take far less damage.', 'Challenge'), K('holy', '🗡️', 'Holy blade', 12, 'magic', 's', 'After 0.8 s a holy blade strikes your target: ×4 damage within 3.5 m, stuns 1 s.', 'Holy')],
  dz_mecha: [K('tank', '🚜', 'Tank mode', 12, 'zap', 'w', 'Tank mode for 6 s: a 2 m electric shockwave every 0.25 s, ×1 damage, stunned 0.3 s.', 'Tank'), K('turret', '🗼', 'Tesla turret', 14, 'zap', 'w', 'Drop a tesla turret that fires shock bolts for 12 s.', 'Turret'), K('missiles', '🚀', 'Shock missiles', 7, 'zap', 'a', 'Up to 6 guided shock missiles at enemies within 16 m: ×2 damage and a 2 m electric burst.', 'Missiles'), K('energyshield', '🔰', 'Energy shield', 16, 'magic', 'w', 'Energy shield: no damage for 4 s and 20% health back.', 'Barrier')],
  dz_dino: [K('devour', '😋', 'Devour', 9, 'crit', 's', 'Bite an enemy within 3.2 m: a weak one (under 40% health) is swallowed whole and heals you 25%; otherwise ×3 damage (a boss is never swallowed).'), K('tail', '💨', 'Tail sweep', 5, 'swing', 's', 'A tail sweep all around: ×1.8 damage within 3.6 m and a big knock-back.', 'Tail'), K('roar', '📢', 'Terrifying roar', 12, 'alert', 'w', 'Roar: enemies within 9 m flee in fear for 4 s (a boss is only slowed).', 'Roar'), K('giant', '🦖', 'Giant form', 18, 'boom', 'w', 'Giant form for 10 s: twice as big, +60% damage, a quarter less damage taken, and your steps shake the ground.', 'Giant')],
  dz_fairy: [K('heal', '💖', 'Healing flowers', 12, 'magic', 'w', 'Healing flowers for 8 s: stay within 4 m to heal 3% every half second.', 'Flowers'), K('hover', '🦋', 'Float', 10, 'magic', 'w', 'Float for 8 s: ground attacks miss you.'), K('charm', '💘', 'Charm', 14, 'magic', 'a', 'Charm your target for 8 s: it fights the other creatures (a boss is only slowed).'), K('roots', '🌳', 'Binding roots', 14, 'magic', 'w', 'Binding roots within 6 m: ×1 damage, stuck for 4 s, then 8 more pulses that heal you.', 'Roots')],
  dz_pirate: [K('cannon', '💣', 'Cannon', 12, 'boom', 'w', 'Set a cannon that fires for 10 s.'), K('hook', '🪝', 'Hook', 6, 'swing', 'a', 'Hook the nearest enemy within 14 m and pull it to you: ×1.5 damage, stunned 2 s.'), K('parrot', '🦜', 'Scout parrot', 10, 'alert', 'a', 'Your parrot marks every enemy within 12 m for 8 s: they take +50% damage, and the mark itself hits for ×0.5.', 'Parrot'), K('cannons', '💥', 'Cannon rain', 14, 'boom', 'a', 'A broadside of 12 cannonballs around your target, ×1.5 damage within 2 m each.', 'Broadside')],
  dz_superhero: [K('flight', '🦸', 'Take flight', 3, 'magic', 'w', 'Fly for 12 s (press again to land): ground attacks miss you.', 'Fly'), K('dive', '☄️', 'Meteor dive', 6, 'boom', 's', 'Dive 4 m ahead and crash: ×2 damage within 5 m, ×4 if you were flying; stuns 1 s.', 'Dive'), K('sweep', '👀', 'Laser gaze', 7, 'zap', 'a', 'Twin eye lasers sweep a 13 m line, 1 m wide, across the front for 1.2 s: ×1 damage per touch.', 'Gaze'), K('boulder', '🪨', 'Boulder throw', 10, 'boom', 'a', 'Lob a giant rock at the nearest enemy within 14 m (8 m ahead if none): lands in 0.6 s for ×3.2 damage in a 4.5 m blast, launching enemies upward.', 'Boulder')],
  dz_vampire: [K('drain', '🩸', 'Life drain', 7, 'magic', 'a', 'Drain your target for 2.1 s: 7 bites of ×0.7 damage, each heals you 3.5%.', 'Drain'), K('bats', '🦇', 'Bat form', 9, 'poof', 'w', 'Become bats for 2.5 s: untouchable.', 'Bat form'), K('batcircle', '🦇', 'Bat swarm', 12, 'poof', 'w', 'Five bats circle you for 8 s, biting enemies and healing you.', 'Swarm'), K('bloodnova', '🌕', 'Blood moon', 15, 'magic', 'w', 'Blood moon for 6 s: enemies within 7 m take ×0.3 damage every 0.5 s and every hit heals you 40%.', 'Blood moon')],
  dz_snowman: [K('snowball', '⚪', 'Rolling snowball', 7, 'freeze', 'a', 'Roll a growing snowball 21 m: ×3 damage to everything it passes, stunned 2 s.', 'Snowball'), K('decoy', '⛄', 'Snow decoy', 12, 'poof', 'w', 'A snow decoy for 6 s: enemies within 8 m are blinded, then it bursts for ×2.5 damage within 4 m.', 'Decoy'), K('icefloor', '🧊', 'Ice rink', 12, 'freeze', 'w', 'An 8 s ice rink 6 m around you: enemies on it are slowed.', 'Rink'), K('iceage', '❄️', 'Ice age', 16, 'freeze', 'w', 'Freeze every enemy within 8 m for 3 s, then shatter them for ×2.8 damage.', 'Ice age')],
  dz_army: [S('volley', '🔫', 7, 'Volley'), K('turret', '🧱', 'Sentry turret', 12, 'zap', 'w', 'Drop a sentry turret that shoots for 12 s.', 'Sentry'), K('smoke', '💨', 'Smoke screen', 10, 'poof', 'w', 'A smoke cloud lasts 5 s within 5 m: enemies inside are blinded and you stay hidden while inside.', 'Smoke'), K('missiles', '🚀', 'Guided rockets', 14, 'boom', 'a', 'Up to 6 guided rockets at enemies within 16 m: ×2 damage and a 2 m blast.', 'Rockets')],
  dz_navy: [S('anchor', '⚓', 8, 'Anchor'), K('hook', '🪝', 'Grappling hook', 6, 'swing', 'a', 'Hook the nearest enemy within 14 m and pull it to you: ×1.5 damage, stunned 2 s.', 'Hook'), K('cannons', '💣', 'Cannon barrage', 14, 'boom', 'a', 'A broadside of 12 cannonballs around your target, ×1.5 damage within 2 m each.', 'Barrage'), S('tsunami', '🌊', 12, 'Surf')],
  dz_aodai: [S('lotus', '🪷', 9, 'Lotus'), K('silk', '🎀', 'Silk ribbons', 10, 'swing', 's', 'Five piercing silk ribbons fan out 11 m: ×0.9 damage each, and enemies are tangled for 0.6 s.', 'Ribbons'), K('charm', '💖', 'Charm', 12, 'magic', 'a', 'Charm your target for 8 s: it fights the other creatures (a boss is only slowed).'), S('starfall', '🌠', 16, 'Starfall')],
  dz_aodai_man: [S('dragon', '🐉', 8, 'Dragon'), K('breath', '🔥', 'Dragon breath', 10, 'boom', 's', 'A cone of 9 fire bursts roars 7 m ahead: ×0.9 damage each, enemies are knocked back.', 'Breath'), K('charge', '🐎', 'Charge', 9, 'swing', 's', 'Charge 11 m forward, untouchable, ×3 damage to every enemy on the way.'), S('thunder', '⚡', 14, 'Thunder')],
  dz_usa: [S('eagle', '🦅', 8, 'Eagle'), K('shield', '🛡️', 'Raise shield', 10, 'magic', 'w', 'Raise your shield: no damage for 4 s.', 'Shield'), K('cannon', '💣', 'Field cannon', 12, 'boom', 'w', 'Set a cannon that fires for 10 s.', 'Cannon'), S('nova', '🌵', 14, 'Thorns')],
  dz_vietnam: [S('goldstar', '⭐', 9, 'Star'), K('roots', '🎋', 'Bamboo roots', 12, 'magic', 'w', 'Binding roots within 6 m: ×1 damage, stuck for 4 s, then 8 more pulses that heal you.', 'Roots'), K('holy', '✨', 'Holy strike', 14, 'magic', 's', 'After 0.8 s a holy blade strikes your target: ×4 damage within 3.5 m, stuns 1 s.', 'Holy'), S('inferno', '🔥', 15, 'Inferno')],
};
export const isKit = id => !!KITS[id];
const cache = {};
/** One skill of a kit, ready for the HUD and the cast: {op, sp, icon, name, short, cd, sound, pose, text, sid}. Specials come from skills-special.mjs. */
export function kitInfo(id, index) {
  const key = id + index; let k = cache[key]; if (k) return k;
  const row = KITS[id]?.[index]; if (!row) return null;
  const sp = row.sp ? SPECIALS[row.sp] : null;
  return cache[key] = { op: row.op, sp: row.sp ?? '', icon: row.icon, name: sp?.name ?? row.name, short: row.short ?? '', cd: row.cd, sound: sp?.sound ?? row.sound, pose: sp?.pose ?? row.pose, text: sp?.text ?? row.text, dmg: sp?.damage ?? 0, sid: key };
}
/** The accent colour of a disguise (the reference's disguise colour): looks and the weapon-free trail use it. */
export const KIT_COLOR = { dz_ninja: '#c9c9ff', dz_mage: '#7f6fff', dz_knight: '#fff3c4', dz_mecha: '#6ff2ff', dz_dino: '#5fbf5a', dz_fairy: '#ff9ec8', dz_pirate: '#ffc93c', dz_superhero: '#3f6fff', dz_vampire: '#b0203a', dz_snowman: '#9fe8ff', dz_army: '#6b7a3a', dz_navy: '#1e3a8a', dz_aodai: '#ff8fb1', dz_aodai_man: '#23408f', dz_usa: '#d6283a', dz_vietnam: '#da251d' };
